'use strict';

const { contextBridge, ipcRenderer } = require('electron');

const call = (channel) => (...args) => ipcRenderer.invoke(channel, ...args);

contextBridge.exposeInMainWorld('api', {
  getConfig: call('config:get'),
  setConfig: call('config:set'),
  chooseDir: call('config:chooseDir'),
  openDataDir: call('config:openDir'),
  loadService: call('service:load'),
  saveService: call('service:save'),
  loadDay: call('day:load'),
  dayRevs: call('day:revs'),
  loadMonth: call('month:load'),
  loadRange: call('range:load'),
  loadUsers: call('users:load'),
  saveUsers: call('users:save'),
  loadAgents: call('agents:load'),
  saveAgents: call('agents:save'),
  loadSite: call('site:load'),
  sitesOverview: call('sites:overview'),
  selectSite: call('sites:select'),
  renameSite: call('sites:rename'),
  siteInfo: call('sites:info'),
  invList: call('inv:list'),
  invSaveCategories: call('inv:saveCategories'),
  invSaveArticle: call('inv:saveArticle'),
  invDeleteArticle: call('inv:deleteArticle'),
  invAddMovement: call('inv:addMovement'),
  invDeleteMovement: call('inv:deleteMovement'),
  invHistory: call('inv:history'),
  listSupervisors: call('sup:list'),
  saveSupervisor: call('sup:save'),
  removeSupervisor: call('sup:remove'),
  verifyPin: call('auth:verify'),
  siteDashboard: call('dashboard:site'),
  saveSite: call('site:save'),
  loadNcTypes: call('nc:load'),
  saveNcTypes: call('nc:save'),
  listTasks: call('tasks:list'),
  saveTask: call('tasks:save'),
  deleteTask: call('tasks:delete'),
  pickPhotos: call('photo:pick'),
  savePhotoData: call('photo:saveData'),
  readPhoto: call('photo:read'),
  openPhoto: call('photo:open'),
  exportExcel: call('excel:export'),
  openFile: call('excel:open'),
  pickImport: call('excel:pick'),
  runImport: call('excel:import'),
  print: call('print'),
  checkUpdate: call('update:check'),
  installUpdate: call('update:install'),
  openUpdateDir: call('update:openDir'),
});
